### ISSUE TITLE
Missing Callback source file

### ISSUE THREAD

**Issue by TennisAndy** [msesma/Karchitec#3]
Hi, I compile this project and find missing com.paradigmadigital.karchitect.platform.Callback file, can you upload this file?

**Comment by msesma** [comment]
That file doesn't exist. Callback is a TypeAlias under
`com.paradigmadigital.karchitect.platform.TypeAliases` and is imported in several files (Like RefreshUseCase) with
`import com.paradigmadigital.karchitect.platform.Callback`
What can be confusing. Remove that inport and see if autoimport recovers it.

**Comment by TennisAndy** [comment]
Well, I know this is not a problem now, Thank you.
